version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 19777:1972
      - 52777:52773
      - 53773
    volumes:
      - ./:/irisdev/app
